### ISSUE TITLE
View组件是不是暂不支持引入的css样式?

### ISSUE THREAD

**Issue by reed-soul** [caigehui/react-wxeap#8]
我要给一个View设置效果，当点击时改变它的背景色设置阴影，我写了一个css文件，用：active实现，引入后，没有效果，但如果将View改成div就可以实现.

**Comment by caigehui** [comment]
指定classname不行吗？

**Comment by reed-soul** [comment]
@caigehui 后来发现不是View组件的原因，我发现给子元素设置了背景色，用伪类无法对其进行样式覆盖，将包含的子元素div的背景色去掉放到上层父元素就可以了
